### ISSUE TITLE
Warning When Updating PhpStan

### ISSUE THREAD

**Issue by sojeda** [worksome/coding-style#58]
When you update PhpStan, every time you run the command it shows the following:

```
⚠️  You're using a deprecated config option checkMissingIterableValueType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing array typehints.

If you want to continue ignoring missing typehints from arrays,
add missingType.iterableValue error identifier to your ignoreErrors:

parameters:
        ignoreErrors:
                -
                        identifier: missingType.iterableValue
```

I'm leaving this issue here, and as soon as I can, I will likely send a PR if no one has done it before.

File:
`worksome/coding-style/larastan.neon`

**Comment by owenvoke** [comment]
Hi @sojeda, yeah, we are hitting the same warning.

I was working on this locally the other day, however forgot to open a PR.

My main thought is to remove the option completely. I personally dislike ignoring all typehints for iterables, so I'm planning on bringing this up, and baseline any errors that show.

However, this would be classed as a breaking change probably. The alternative is to continue disabling all errors with the `missingType.iterableValue` identifier.

I'll bring this up internally within Worksome to see how we are wanting to handle it for our own projects.

**Comment by owenvoke** [comment]
@sojeda, I've updated the package to use the solution of ignoring errors of type `missingType.iterableValue`, this matches our current solution.

I think in future, we may think about changing this. But feel free to update to `2.11.x` which will remove the deprecation warning. 👍🏻

**Comment by sojeda** [comment]
Thanks @owenvoke
